[build]
  base = "baisoft-marketplace/frontend"
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_PUBLIC_API_URL = "https://baisoft-production.up.railway.app/api"
  NEXT_PUBLIC_SITE_NAME = "Baisoft Marketplace"
