[phases.setup]
nixPkgs = ["python312", "postgresql"]

[phases.install]
cmds = ["cd baisoft-marketplace && pip install -r requirements.txt"]

[phases.build]
cmds = ["cd baisoft-marketplace && python manage.py collectstatic --noinput"]

[start]
cmd = "cd baisoft-marketplace && python manage.py migrate && gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT"
